# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: release
on: [workflow_dispatch]

permissions:
  contents: write

env:
  PROJ_NAME: PeacefulProgression

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'
          cache: gradle
      - name: Loom Cache
        uses: actions/cache@v4
        with:
          path: "**/.gradle/loom-cache"
          key: "${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}"
          restore-keys: "${{ runner.os }}-gradle-"
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Read minecraft version from gradle.properties
        id: read-minecraft-version
        run: |
          minecraft_version=$(grep '^minecraft_version=' gradle.properties | cut -d'=' -f2)
          echo "minecraft_version=$minecraft_version" >> $GITHUB_ENV
      - name: Read mod version from gradle.properties
        id: read-mod-version
        run: |
          mod_version=$(grep '^mod_version=' gradle.properties | cut -d'=' -f2)
          echo "mod_version=$mod_version" >> $GITHUB_ENV
      - name: Create Release
        uses: "ncipollo/release-action@v1"
        with:
          allowUpdates: true
          commit: ${{ github.ref_name }}
          tag: ${{ env.minecraft_version }}-${{ env.mod_version }}
          name: ${{ env.minecraft_version }}-${{ env.mod_version }}
          omitBodyDuringUpdate: true
          artifacts: "build/libs/*"
          draft: true
          prerelease: false